theseus_user:
    resource: "@TheseusUserBundle/Resources/config/routing.yml"
    prefix: /

theseus_application_main:
    resource: "@TheseusApplicationBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /2.1/fr/main