security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: true
            form_login:
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: theseus.login_manager
            logout: 
                path: fos_user_security_logout
                target: fos_user_security_login
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: theseus.login_manager
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous: true
            context: auth

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
